### ISSUE TITLE
type: chistian?

### ISSUE THREAD

**Issue by zvezdochiot** [mauvilsa/imgtxtenh#9]
For a certain material (engravings), the Chistian method is preferable. Your opinion?

**Comment by zvezdochiot** [comment]
Chistian == wolf.

**Comment by mauvilsa** [comment]
This all depends on the actual task you are addressing and the amount of data you have. And anyway what works best needs to be determined experimentally. If the task is recognition you have a lot of data available, probably is best to let a deep learning model learn to extract features from the original images instead of using a rule based approach such as Sauvola or Wolf.

**Comment by zvezdochiot** [comment]
@mauvilsa say:
>If the task is recognition

Not. The task is threshold the image of the page, even if it contains drawings, such as engravings.

![Engraving Page](https://i111.fastpic.ru/big/2019/1202/6d/20028a272e1680f689c22bb491816b6d.jpg)

**Comment by mauvilsa** [comment]
My comment stands. It all depends on your task. I have no experience on thresholding images just for the sake of thresholding, without a subsequent goal such as recognition. I guess you do have an end goal which is not just thresholding. But anyway depending on what the end goal is, there might be some research papers about it, though I would be familiar with them since I have only worked on recognition tasks. Regardless if there is something in the literature you should test all potential techniques with your data to see what best works for your goal.

**Comment by zvezdochiot** [comment]
@mauvilsa say:
>what best works for your goal.

Ok. https://github.com/ImageProcessing-ElectronicPublications/imgtxtenh/commit/bc23c7f98ec619c1f23ca5e04408898fc2508f0c

PS: While it crashes. In another project it works. I'm debugging.

**Comment by zvezdochiot** [comment]
Fixed #10
